# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 jlurg
<#
.SYNOPSIS
    Writes the build information header ls_build_info_gen.h of the DCU IAR build.

.DESCRIPTION
    Content: system version from VERSION, abbreviated git commit, dirty flag and BuildType.
    Debug and Hil always report DEV. Release reports RELEASE on an exact tag vX.Y.Z, RC on an
    exact tag vX.Y.Z-rc.N and DEV otherwise. The header is generated at build time and is not
    committed.

    Project setting (Build Actions, pre-build command line):
    pwsh -NoProfile -ExecutionPolicy Bypass -File "$PROJ_DIR$\..\scripts\iar\New-BuildInfo.ps1" -OutDir "$PROJ_DIR$\$CONFIG_NAME$\gen" -Config "$CONFIG_NAME$"

.PARAMETER OutDir
    Directory of the generated header.

.PARAMETER Config
    Build configuration: Debug, Hil or Release.

.EXAMPLE
    ./firmware/dcu/scripts/iar/New-BuildInfo.ps1 -OutDir firmware/dcu/iar/Release/gen -Config Release
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)] [string] $OutDir,
    [Parameter(Mandatory)] [ValidateSet('Debug', 'Hil', 'Release')] [string] $Config
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot '../DcuTools.psm1') -Force

$repoRoot = Get-DcuRepoRoot
$version = (Get-Content -LiteralPath (Join-Path $repoRoot 'VERSION') -TotalCount 1).Trim()
if ($version -notmatch '^(\d+)\.(\d+)\.(\d+)') { throw "VERSION is not a semantic version: $version" }
$major, $minor, $patch = $Matches[1], $Matches[2], $Matches[3]

$hash = 'unknown'
$dirty = 1
$tag = ''
if (Get-Command git -ErrorAction SilentlyContinue) {
    $hash = (& git -C $repoRoot rev-parse --short=12 HEAD 2>$null)
    if ($LASTEXITCODE -ne 0 -or -not $hash) { $hash = 'unknown' }
    $status = @(& git -C $repoRoot status --porcelain --untracked-files=no 2>$null)
    $dirty = if ($LASTEXITCODE -eq 0 -and $status.Count -eq 0 -and $hash -ne 'unknown') { 0 } else { 1 }
    $tag = (& git -C $repoRoot describe --exact-match --tags HEAD 2>$null)
    if ($LASTEXITCODE -ne 0) { $tag = '' }
}

$buildType = 'DEV'
if ($Config -eq 'Release' -and $dirty -eq 0) {
    if ($tag -match '^v\d+\.\d+\.\d+$') { $buildType = 'RELEASE' }
    elseif ($tag -match '^v\d+\.\d+\.\d+-rc\.\d+$') { $buildType = 'RC' }
}

$header = @"
/* DO NOT EDIT $([char]0x2014) generated by firmware/dcu/scripts/iar/New-BuildInfo.ps1 from VERSION and git */
/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright (c) 2026 jlurg */

/**
 * @file ls_build_info_gen.h
 * @brief Build information of the DCU image (DID 0xF195, `$LSVER`).
 */

#ifndef LS_BUILD_INFO_GEN_H
#define LS_BUILD_INFO_GEN_H

#include "ls_enums_gen.h"

#define LS_BUILD_VERSION_STR   "$version" /**< System version */
#define LS_BUILD_VERSION_MAJOR ($($major)u) /**< Major version */
#define LS_BUILD_VERSION_MINOR ($($minor)u) /**< Minor version */
#define LS_BUILD_VERSION_PATCH ($($patch)u) /**< Patch version */
#define LS_BUILD_GIT_HASH_STR  "$hash" /**< Abbreviated commit */
#define LS_BUILD_DIRTY         ($($dirty)u) /**< 1: uncommitted changes */
#define LS_BUILD_TYPE          LS_BUILD_TYPE_$buildType /**< BuildType */

#endif /* LS_BUILD_INFO_GEN_H */
"@

$target = Join-Path $OutDir 'ls_build_info_gen.h'
if ($PSCmdlet.ShouldProcess($target, 'write build information')) {
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
    $content = $header -replace "`r`n", "`n"
    $existing = if (Test-Path -LiteralPath $target) { [System.IO.File]::ReadAllText($target) } else { '' }
    if ($existing -ne $content) {
        [System.IO.File]::WriteAllText($target, $content, [System.Text.UTF8Encoding]::new($false))
    }
    Write-Output "$target`: $version $hash dirty=$dirty $buildType"
}
