# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 jlurg
"""Shared paths, file helpers and generated-file banners of the code generators."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOL = "tools/codegen/regen.py"
MANIFEST = "interfaces/can/codegen.yaml"

#: Every file written by regen.py carries this text in its first line; stale-file detection
#: only ever touches files that contain it.
GENERATED_MARKER = f"DO NOT EDIT — generated by {TOOL}"

_COMMENT_STYLES = {
    "c": ("/* ", " */"),
    "dart": ("// ", ""),
    "hash": ("# ", ""),
}


class CodegenError(Exception):
    """A source or generator problem that stops code generation."""


def banner(source: str, style: str, tool: str | None = None) -> str:
    """Return the DO NOT EDIT first line for a generated file.

    Args:
        source: repository-relative source the file is generated from.
        style: ``c``, ``dart`` or ``hash``.
        tool: upstream generator (for example ``cantools 44.1.0``) that regen.py runs.
    """
    prefix, suffix = _COMMENT_STYLES[style]
    via = f" ({tool})" if tool else ""
    return f"{prefix}{GENERATED_MARKER}{via} from {source}{suffix}\n"


def is_generated(path: Path) -> bool:
    """True when the first line of ``path`` carries the regen.py marker."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            first = handle.readline()
    except OSError:
        return False
    return GENERATED_MARKER in first


def rel(path: Path) -> str:
    """Repository-relative POSIX path."""
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def load_yaml(path: Path) -> Any:
    """Load a YAML document with the safe loader."""
    try:
        with path.open("r", encoding="utf-8") as handle:
            return yaml.safe_load(handle)
    except (OSError, yaml.YAMLError) as exc:
        raise CodegenError(f"{rel(path)}: {exc}") from exc


def write_text(path: Path, text: str) -> None:
    """Write UTF-8 text with LF line endings, creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def snake_upper(camel: str) -> str:
    """``WindowStopReason`` -> ``WINDOW_STOP_REASON``."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", camel).upper()


def lower_camel(snake: str) -> str:
    """``t_app_ka_ms`` -> ``tAppKaMs``."""
    head, *tail = snake.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)
