# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 jlurg
"""Load and validate bench configuration files."""

import json
import os
from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError

from locksys_hil.config.models import BenchConfig
from locksys_hil.errors import ConfigError

BENCH_ENV = "LOCKSYS_HIL_BENCH"
"""Environment variable naming the bench YAML when ``--hil-bench`` is not given."""


def load_bench_config(path: Path) -> BenchConfig:
    """Load and validate a bench YAML file.

    Raises:
        ConfigError: the file is missing, not YAML or not a valid bench description.
    """
    try:
        data: Any = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise ConfigError(f"cannot read bench configuration {path}: {exc}") from exc
    try:
        return BenchConfig.model_validate(data)
    except ValidationError as exc:
        raise ConfigError(f"invalid bench configuration {path}:\n{exc}") from exc


def resolve_bench_path(option: str | None) -> Path | None:
    """Return the bench YAML from the command-line option or ``LOCKSYS_HIL_BENCH``."""
    value = option or os.environ.get(BENCH_ENV)
    return Path(value).expanduser() if value else None


def bench_schema() -> str:
    """Return the JSON schema of ``BenchConfig`` (committed as ``config/schema``)."""
    schema = BenchConfig.model_json_schema()
    schema["$comment"] = (
        "DO NOT EDIT — generated by 'hil config schema --write' from locksys_hil.config.models"
    )
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
