#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 jlurg
"""Branch-name, merge-matrix and Conventional Commits rules of the LockSys repository.

This module is the executable form of the rules in ``docs/08_process/branching.md`` and
``docs/08_process/commits_and_prs.md``. It is used by the ``pr-policy`` workflow, by the
``conventional-commit-msg`` commit-msg hook and by ``new-branch.sh`` / ``pr-merge.sh``.

Command-line interface (``--format github`` before the sub-command prints errors as
GitHub Actions ``::error::`` workflow commands)::

    conventions.py branch NAME
        Validate a branch name; print its kind (work, release, hotfix, sync, external,
        spike, dependabot, develop, main).

    conventions.py title TITLE [--head BRANCH]
        Validate a pull-request title or commit header (header at most 72 characters,
        subject 3 to 70 characters). ``--head dependabot/...`` lifts the length limits
        for titles generated by Dependabot.

    conventions.py commit-msg FILE
        Validate a commit message file (commit-msg hook). Git-generated merge messages
        and ``fixup!``/``squash!``/``amend!`` commits are accepted.

    conventions.py merge-method --base BASE --head HEAD
        Print the required merge method (``squash`` or ``merge``) for an allowed pair.

    conventions.py pr --base BASE --head HEAD --title TITLE [--author LOGIN] [--body-file FILE]
        Run the pull-request checks of ``pr-policy``: head branch name, allowed base/head
        pair, title and, when ``--body-file`` is given, an issue reference (``Closes #n``,
        ``Fixes #n``, ``Resolves #n`` or ``Refs #n``) unless the pull request is exempt.
        Exempt: author ``dependabot[bot]``, ``sync/*`` heads and release or hotfix pull
        requests into ``main``.

Example step in ``pr-policy.yml``::

    python3 tools/git/conventions.py --format github pr \\
        --base "$BASE_REF" --head "$HEAD_REF" --title "$TITLE" \\
        --author "$AUTHOR" --body-file body.txt

Exit status: 0 when valid, 1 on a policy violation, 2 on usage or I/O errors.

The module depends on the standard library only and supports Python 3.9 or later.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from enum import Enum
from pathlib import Path

EXIT_OK = 0
EXIT_VIOLATION = 1
EXIT_USAGE = 2

WORK_TYPES: tuple[str, ...] = (
    "feature",
    "fix",
    "docs",
    "ci",
    "build",
    "refactor",
    "test",
    "chore",
    "perf",
)
"""Work-branch prefixes; work branches start from and merge into ``develop``."""

RELEASE_FIX_TYPES: tuple[str, ...] = ("fix", "docs", "test", "build")
"""Work-branch prefixes accepted into ``release/X.Y.Z`` during the release freeze."""

HOTFIX_FIX_TYPES: tuple[str, ...] = ("fix", "docs", "test", "build")
"""Work-branch prefixes accepted into ``hotfix/X.Y.Z``."""

COMMIT_TYPES: tuple[str, ...] = (
    "feat",
    "fix",
    "perf",
    "refactor",
    "test",
    "docs",
    "build",
    "ci",
    "chore",
    "revert",
)
"""Conventional Commits types."""

SCOPES: tuple[str, ...] = (
    "dcu",
    "cgw",
    "app",
    "hil",
    "can",
    "proto",
    "libs",
    "docs",
    "ci",
    "build",
    "tools",
    "deps",
    "deps-dev",
    "release",
    "repo",
)
"""Conventional Commits scopes."""

MAX_BRANCH_LENGTH = 60
HEADER_MAX_LENGTH = 72
SUBJECT_MAX_LENGTH = 70
SUBJECT_MIN_LENGTH = 3
EXEMPT_AUTHORS: tuple[str, ...] = ("dependabot[bot]",)

SQUASH = "squash"
MERGE = "merge"


class BranchKind(Enum):
    """Branch categories of the branching model."""

    WORK = "work"
    RELEASE = "release"
    HOTFIX = "hotfix"
    SYNC = "sync"
    EXTERNAL = "external"
    SPIKE = "spike"
    DEPENDABOT = "dependabot"
    DEVELOP = "develop"
    MAIN = "main"


_SLUG = r"[a-z0-9]+(?:-[a-z0-9]+)*"
_SEMVER = r"[0-9]+\.[0-9]+\.[0-9]+"

BRANCH_PATTERNS: tuple[tuple[BranchKind, re.Pattern[str]], ...] = (
    (BranchKind.WORK, re.compile(rf"^(?:{'|'.join(WORK_TYPES)})/[0-9]+-{_SLUG}$")),
    (BranchKind.RELEASE, re.compile(rf"^release/{_SEMVER}$")),
    (BranchKind.HOTFIX, re.compile(rf"^hotfix/{_SEMVER}$")),
    (BranchKind.SYNC, re.compile(rf"^sync/main-to-(?:develop|release-{_SEMVER})-v{_SEMVER}$")),
    (BranchKind.EXTERNAL, re.compile(rf"^ext/[0-9]+-{_SLUG}$")),
    (BranchKind.SPIKE, re.compile(rf"^spike/[0-9]+-{_SLUG}$")),
    (BranchKind.DEPENDABOT, re.compile(r"^dependabot/.+$")),
    (BranchKind.DEVELOP, re.compile(r"^develop$")),
    (BranchKind.MAIN, re.compile(r"^main$")),
)

_TITLE_RE = re.compile(
    r"^(?P<type>[a-z]+)(?:\((?P<scopes>[^()]*)\))?(?P<breaking>!)?: (?P<subject>.*)$"
)
_ISSUE_REF_RE = re.compile(
    r"(?im)\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?|refs?)\b:?[ \t]+"
    r"(?:[a-z0-9_.-]+/[a-z0-9_.-]+)?#[0-9]+\b"
)
_AUTOSQUASH_PREFIXES: tuple[str, ...] = ("fixup! ", "squash! ", "amend! ")
_SCISSORS_MARK = "------------------------ >8 ------------------------"


def branch_kind(name: str) -> BranchKind | None:
    """Classify a branch name.

    @param name Branch name without ``refs/heads/``.
    @return The branch kind, or ``None`` when the name matches no pattern.
    """
    for kind, pattern in BRANCH_PATTERNS:
        if pattern.match(name):
            return kind
    return None


def check_branch(name: str) -> list[str]:
    """Validate a branch name.

    @param name Branch name without ``refs/heads/``.
    @return Error messages; empty when the name is valid.
    """
    kind = branch_kind(name)
    if kind is None:
        return [
            f"branch '{name}' does not follow the naming rules: use "
            f"<{'|'.join(WORK_TYPES)}>/<issue>-<slug>, release/X.Y.Z, hotfix/X.Y.Z, "
            "sync/main-to-develop-vX.Y.Z, sync/main-to-release-A.B.C-vX.Y.Z, "
            "ext/<pr>-<slug> or spike/<issue>-<slug>"
        ]
    if kind is not BranchKind.DEPENDABOT and len(name) > MAX_BRANCH_LENGTH:
        return [f"branch '{name}' is {len(name)} characters long (maximum {MAX_BRANCH_LENGTH})"]
    return []


def _work_type(name: str) -> str:
    return name.split("/", 1)[0]


def _sync_target(name: str) -> str:
    """Return the branch a ``sync/main-to-<target>-vX.Y.Z`` branch merges into."""
    target = name[len("sync/main-to-") :].rsplit("-v", 1)[0]
    return "develop" if target == "develop" else "release/" + target[len("release-") :]


def merge_method(base: str, head: str) -> str | None:
    """Return the merge method required for merging ``head`` into ``base``.

    @param base Target branch of the pull request.
    @param head Source branch of the pull request.
    @return ``"squash"`` or ``"merge"``, or ``None`` when the pair is not allowed.
    """
    base_kind = branch_kind(base)
    head_kind = branch_kind(head)
    if base_kind is BranchKind.DEVELOP:
        if head_kind in (BranchKind.WORK, BranchKind.EXTERNAL, BranchKind.DEPENDABOT):
            return SQUASH
        if head_kind is BranchKind.SYNC and _sync_target(head) == base:
            return MERGE
    elif base_kind is BranchKind.MAIN:
        if head_kind in (BranchKind.RELEASE, BranchKind.HOTFIX):
            return MERGE
    elif base_kind is BranchKind.RELEASE:
        if head_kind is BranchKind.WORK and _work_type(head) in RELEASE_FIX_TYPES:
            return SQUASH
        if head_kind is BranchKind.SYNC and _sync_target(head) == base:
            return MERGE
    elif base_kind is BranchKind.HOTFIX:
        if head_kind is BranchKind.WORK and _work_type(head) in HOTFIX_FIX_TYPES:
            return SQUASH
    return None


def check_title(title: str, limit_length: bool = True) -> list[str]:
    """Validate a Conventional Commits header (pull-request title or commit subject line).

    Format: ``<type>[(<scope>[,<scope>...])][!]: <subject>``; the subject starts with a
    lower-case letter or a digit and does not end with a period. The header has at most
    72 characters and the subject 3 to 70 characters.

    @param title Header to validate.
    @param limit_length ``False`` lifts the maximum lengths (titles generated by Dependabot).
    @return Error messages; empty when the header is valid.
    """
    if title.startswith('Revert "'):
        return [f"title '{title}': write reverts as 'revert: <original subject>'"]
    match = _TITLE_RE.match(title)
    if match is None:
        return [f"title '{title}' does not match '<type>(<scope>)!: <subject>'"]
    errors: list[str] = []
    commit_type = match.group("type")
    if commit_type not in COMMIT_TYPES:
        errors.append(f"unknown type '{commit_type}' (allowed: {', '.join(COMMIT_TYPES)})")
    scopes = match.group("scopes")
    if scopes is not None:
        for scope in scopes.split(","):
            if scope not in SCOPES:
                errors.append(f"unknown scope '{scope}' (allowed: {', '.join(SCOPES)})")
    subject = match.group("subject")
    if not re.match(r"^[a-z0-9]", subject):
        errors.append("subject must start with a lower-case letter or a digit")
    if subject.endswith("."):
        errors.append("subject must not end with a period")
    if subject != subject.rstrip():
        errors.append("subject must not end with whitespace")
    if len(subject) < SUBJECT_MIN_LENGTH:
        errors.append(f"subject must have at least {SUBJECT_MIN_LENGTH} characters")
    if limit_length and len(subject) > SUBJECT_MAX_LENGTH:
        errors.append(f"subject is {len(subject)} characters long (maximum {SUBJECT_MAX_LENGTH})")
    if limit_length and len(title) > HEADER_MAX_LENGTH:
        errors.append(f"header is {len(title)} characters long (maximum {HEADER_MAX_LENGTH})")
    return errors


def strip_git_comments(message: str, comment_char: str = "#") -> str:
    """Return a commit message without Git comment lines and verbose diff.

    @param message Raw content of the commit message file.
    @param comment_char Git ``core.commentChar`` (``#`` by default).
    @return The message as Git stores it with the default ``strip`` clean-up mode.
    """
    kept: list[str] = []
    for line in message.splitlines():
        if line.startswith(comment_char):
            if _SCISSORS_MARK in line:
                break
            continue
        kept.append(line)
    return "\n".join(kept).strip("\n")


def check_commit_message(message: str) -> list[str]:
    """Validate a commit message as written by Git into the commit message file.

    @param message Raw content of the commit message file.
    @return Error messages; empty when the message is valid.
    """
    text = strip_git_comments(message)
    if not text.strip():
        return []
    lines = text.split("\n")
    header = lines[0]
    if header.startswith("Merge ") or header.startswith(_AUTOSQUASH_PREFIXES):
        return []
    errors = check_title(header)
    if len(lines) > 1 and lines[1].strip():
        errors.append("separate the header from the body with a blank line")
    return errors


def is_issue_link_exempt(base: str, head: str, author: str | None) -> bool:
    """Tell whether a pull request is exempt from the linked-issue requirement.

    @param base Target branch.
    @param head Source branch.
    @param author Login of the pull-request author, if known.
    @return ``True`` for Dependabot, ``sync/*`` heads and release/hotfix merges into ``main``.
    """
    if author in EXEMPT_AUTHORS:
        return True
    head_kind = branch_kind(head)
    if head_kind is BranchKind.SYNC:
        return True
    return branch_kind(base) is BranchKind.MAIN and head_kind in (
        BranchKind.RELEASE,
        BranchKind.HOTFIX,
    )


def has_issue_reference(body: str) -> bool:
    """Tell whether a pull-request body references an issue.

    @param body Pull-request body.
    @return ``True`` when a ``Closes``/``Fixes``/``Resolves``/``Refs`` ``#n`` reference exists.
    """
    return _ISSUE_REF_RE.search(body) is not None


def check_pull_request(
    base: str,
    head: str,
    title: str,
    author: str | None = None,
    body: str | None = None,
) -> list[str]:
    """Run all pull-request policy checks.

    @param base Target branch.
    @param head Source branch.
    @param title Pull-request title.
    @param author Login of the pull-request author, if known.
    @param body Pull-request body; the issue-reference check is skipped when ``None``.
    @return Error messages; empty when the pull request complies.
    """
    errors = check_branch(head)
    if not errors and merge_method(base, head) is None:
        errors.append(f"merging '{head}' into '{base}' is not allowed by the branching model")
    head_kind = branch_kind(head)
    errors += check_title(title, limit_length=head_kind is not BranchKind.DEPENDABOT)
    if (
        body is not None
        and not is_issue_link_exempt(base, head, author)
        and not has_issue_reference(body)
    ):
        errors.append("the pull-request body must reference an issue (for example 'Closes #12')")
    return errors


def _escape_workflow_command(text: str) -> str:
    return text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def _report(errors: Sequence[str], output_format: str) -> int:
    for error in errors:
        if output_format == "github":
            print(f"::error title=pr-policy::{_escape_workflow_command(error)}")
        else:
            print(f"error: {error}", file=sys.stderr)
    return EXIT_VIOLATION if errors else EXIT_OK


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="conventions.py",
        description="LockSys branch, merge and Conventional Commits rules.",
    )
    parser.add_argument("--format", choices=("text", "github"), default="text")
    sub = parser.add_subparsers(dest="command", required=True)

    p_branch = sub.add_parser("branch", help="validate a branch name")
    p_branch.add_argument("name")

    p_title = sub.add_parser("title", help="validate a PR title or commit header")
    p_title.add_argument("title")
    p_title.add_argument("--head", help="head branch of the pull request")

    p_msg = sub.add_parser("commit-msg", help="validate a commit message file")
    p_msg.add_argument("file", type=Path)

    p_merge = sub.add_parser("merge-method", help="print the merge method for a base/head pair")
    p_merge.add_argument("--base", required=True)
    p_merge.add_argument("--head", required=True)

    p_pr = sub.add_parser("pr", help="run all pull-request policy checks")
    p_pr.add_argument("--base", required=True)
    p_pr.add_argument("--head", required=True)
    p_pr.add_argument("--title", required=True)
    p_pr.add_argument("--author")
    p_pr.add_argument("--body-file", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Command-line entry point.

    @param argv Arguments without the program name; ``None`` uses ``sys.argv``.
    @return Process exit status.
    """
    args = _build_parser().parse_args(argv)
    fmt: str = args.format
    try:
        if args.command == "branch":
            errors = check_branch(args.name)
            if not errors:
                kind = branch_kind(args.name)
                print(kind.value if kind is not None else "")
            return _report(errors, fmt)
        if args.command == "title":
            head_kind = branch_kind(args.head) if args.head else None
            limit_length = head_kind is not BranchKind.DEPENDABOT
            return _report(check_title(args.title, limit_length), fmt)
        if args.command == "commit-msg":
            message = args.file.read_text(encoding="utf-8", errors="replace")
            return _report(check_commit_message(message), fmt)
        if args.command == "merge-method":
            method = merge_method(args.base, args.head)
            if method is None:
                return _report([f"merging '{args.head}' into '{args.base}' is not allowed"], fmt)
            print(method)
            return EXIT_OK
        body = None
        if args.body_file is not None:
            body = args.body_file.read_text(encoding="utf-8", errors="replace")
        return _report(check_pull_request(args.base, args.head, args.title, args.author, body), fmt)
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_USAGE


if __name__ == "__main__":
    sys.exit(main())
